name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker services
        run: docker-compose build

      - name: Start services for testing
        run: docker compose up -d

      - name: Wait and check containers
        run: docker ps -a

    
