name: Build and Deploy

on:
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Stop and remove containers if running (ignore errors)
      - name: Stop existing containers
        run: |
          docker stop todo-backend
          docker stop todo-frontend
          docker rm todo-backend
          docker rm todo-frontend 
          docker system prune -a -f 

      - name: Build backend image
        run: docker build -t todo-backend ./backend

      - name: Build frontend image
        run: docker build -t todo-frontend ./frontend

      - name: Start containers
        run: docker-compose -f docker-compose.yml up -d

      - name: List running containers
        run: docker ps
