name: CI/CD Pipeline

on:
  push:
    branches: [main1]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: remove old Backend and frontend containers
        run: |
         sudo docker stop todo-frontend
         sudo docker stop todo-backend
         sudo docker rm todo-frontend 
         sudo docker rm todo-backend
         sudo docker system prune -a -f
        
        

      - name: Build Docker services and Start services container
        run: |
         sudo docker compose build
         sudo docker compose up -d
        
         
         
         #sudo docker rm todo-traefik
 
    
